#! python


def build(ctx):
    ctx(
        features='run_py_script',
        source='data_management.py',
        target=ctx.path_to(ctx, 'OUT_DATA', 'sfc_clean_pd.pkl'),
        name='sfc_clean_pd'
    )
