#! python


def build(ctx):
        ctx(
            features='run_py_script',
            source='final.py',
            deps=[
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'data_to_output.pkl'),
            ],
            target=[ctx.path_to(ctx, 'OUT_FIGURES', 'histogram_networth.png'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'histogram_income.png'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'lorenz_income.png'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'lorenz_networth.png'),
            ctx.path_to(ctx, 'OUT_TABLES', 'net_worth_deciles_table.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'net_worth_quintiles_table.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'income_deciles_table.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'income_quintiles_table.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'age_partition.tex'),
            ],
        )
