#! python

import os
def build(ctx):
    ctx(
        features='run_py_script',
        source='analysis.py',
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'sfc_clean_pd.pkl'),
            ctx.path_to(ctx, 'IN_FUNCTIONS', 'myfunctions.py'),
        ],
        target=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'data_to_output.pkl'),
        ],
    )
