#! python


def build(ctx):
    ctx.recurse('data_management')
    ctx.recurse('tests_functions')
    ctx.recurse('analysis')
    ctx.recurse('final')
    ctx.add_group()
    ctx.recurse('paper')
    ctx.recurse('documentation')
