#! python


def build(ctx):
        ctx(
            features='tex',
            source='final_project.tex',
            prompt=1,
            name='final_project'
        )
        # Install to the project root.
        ctx.install_files(
            ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
            'final_project.pdf'
        )
        # Running LaTeX processes in parallel leads to
        # too many potential problems.
        ctx.add_group()
